#!/usr/bin/env python3

## @package generate_roman_table
# This script generates file roman_table.h
# with string array @p roman_table of Roman numeral 
# defined in it. File roman_table.h can be included by
# @code{.c} #include "roman_table.h" @endcode
#
# Script uses package @c roman to generate Roman numerals.

import roman

print("#ifndef ROMAN_TABLE_H")
print("#define ROMAN_TABLE_H\n")
print("// Autogenerated roman numeral table")
print("const char* roman_table[] = {")
for i in range(1, 101):
    print(f'\t"{roman.toRoman(i)}",  // {i}')
print("};\n")
print("#endif")
