#include <string.h>
#include "roman_table.h"

/** Transform Arabic numeral to Roman numeral.
 *
 * @param num Arabic numeral. Must be between 1 and 100
 * @return Roman numeral as a string between I and C 
 * if input parameter @p num is correct or NULL otherwise 
 *
 * Method gets Roman numerals from string array defined in autogenerated 
 * file roman_table.h.
 */
const char *get_roman_numeral(int num)
{
	if(num < 1 || num > 100)
	{
		return NULL;
	}

	return roman_table[num - 1];
}

/** Transform Roman numeral to Arabic numeral.
 *
 * @param roman Roman numeral. Must be between I and C
 * @return Arabic numeral between 1 and 100 if input 
 * parameter @p roman is correct or -1 otherwise
 *
 * Method uses string array of Roman numerals defined in autogenerated
 * file roman_table.h
 */
int get_arabic_numeral(const char *roman)
{
	for(int i = 0; i < 100; i++)
	{
		if(!strcmp(roman, roman_table[i]))
		{
			return i + 1;
		}
	}

	return -1;
}

