#!/usr/bin/env python3
import roman

print("#ifndef ROMAN_TABLE_H")
print("#define ROMAN_TABLE_H\n")
print("// Autogenerated roman numeral table")
print("const char* roman_table[] = {")
for i in range(1, 101):
    print(f'\t"{roman.toRoman(i)}",  // {i}')
print("};\n")
print("#endif")
